server:
  port: 8080

spring:
  application:
    name: Library-Management-System
  datasource:
    url: jdbc:postgresql://localhost:5234/library_management_system
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    name: library_management_system
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
        format_sql: true
    show-sql: true
#jwtKey: ${SECRET_KEY}